In [1]:
import garminconnect

from getpass import getpass
import os

email = os.getenv("GARMIN_EMAIL")
password = os.getenv("GARMIN_PASSWORD")

garmin = garminconnect.Garmin(email, password)
garmin.login()

print('Display Name: ', garmin.display_name)

Display Name:  c1271d50-beb4-4512-befe-7bc4b2b658d9

In [2]:
import os

GARTH_HOME = os.getenv("GARTH_HOME", "~/.garth")
garmin.garth.dump(GARTH_HOME)

In [3]:
from datetime import date, timedelta

DATE_1 = "2024-12-29"
DATE_2 = "2025-01-14"

In [4]:
import pandas as pd

In [5]:


yesterday = date.today() - timedelta(days=4)
yesterday = yesterday.isoformat()
yesterday

garmin.get_steps_data(yesterday)[:2]

[{'startGMT': '2025-01-12T00:00:00.0',
  'endGMT': '2025-01-12T00:15:00.0',
  'steps': 302,
  'pushes': 0,
  'primaryActivityLevel': 'sedentary',
  'activityLevelConstant': False},
 {'startGMT': '2025-01-12T00:15:00.0',
  'endGMT': '2025-01-12T00:30:00.0',
  'steps': 0,
  'pushes': 0,
  'primaryActivityLevel': 'sedentary',
  'activityLevelConstant': True}]

### Import Daily Step data

In [8]:
total_steps_df = pd.DataFrame(garmin.get_daily_steps(DATE_1, DATE_2))
total_steps_df.head()

  calendarDate  totalSteps  totalDistance  stepGoal
0   2024-12-29         NaN            NaN       NaN
1   2024-12-30      7706.0         6830.0   10000.0
2   2024-12-31     17390.0        14201.0   10000.0
3   2025-01-01      3703.0         3024.0   10000.0
4   2025-01-02      4126.0         3407.0   10000.0

In [16]:
garmin.get_activities_by_date(DATE_1, DATE_2)[0]

{'activityId': 18007394591,
 'activityName': 'Indoor Cycling',
 'startTimeLocal': '2025-01-14 16:12:45',
 'startTimeGMT': '2025-01-14 16:12:45',
 'activityType': {'typeId': 25,
  'typeKey': 'indoor_cycling',
  'parentTypeId': 2,
  'isHidden': False,
  'trimmable': True,
  'restricted': False},
 'eventType': {'typeId': 9, 'typeKey': 'uncategorized', 'sortOrder': 10},
 'distance': 0.0,
 'duration': 2154.448974609375,
 'elapsedDuration': 2154.448974609375,
 'movingDuration': 0.0,
 'averageSpeed': 0.0,
 'hasPolyline': False,
 'hasImages': False,
 'ownerId': 114846541,
 'ownerDisplayName': 'c1271d50-beb4-4512-befe-7bc4b2b658d9',
 'ownerFullName': 'Hayden',
 'ownerProfileImageUrlSmall': 'https://s3.amazonaws.com/garmin-connect-prod/profile_images/5958c9a3-c0bb-4074-9e22-fb3231c39ab1-prth.png',
 'ownerProfileImageUrlMedium': 'https://s3.amazonaws.com/garmin-connect-prod/profile_images/5958c9a3-c0bb-4074-9e22-fb3231c39ab1-prfr.png',
 'ownerProfileImageUrlLarge': 'https://s3.amazonaws.com/garmin-connect-prod/profile_images/5958c9a3-c0bb-4074-9e22-fb3231c39ab1-prof.png',
 'calories': 402.0,
 'bmrCalories': 53.0,
 'averageHR': 142.0,
 'maxHR': 173.0,
 'userRoles': ['SCOPE_GOLF_API_READ',
  'SCOPE_ATP_READ',
  'SCOPE_DIVE_API_WRITE',
  'SCOPE_COMMUNITY_COURSE_ADMIN_READ',
  'SCOPE_DIVE_API_READ',
  'SCOPE_DI_OAUTH_2_CLIENT_READ',
  'SCOPE_CONNECT_WRITE',
  'SCOPE_COMMUNITY_COURSE_WRITE',
  'SCOPE_MESSAGE_GENERATION_READ',
  'SCOPE_DI_OAUTH_2_CLIENT_REVOCATION_ADMIN',
  'SCOPE_CONNECT_WEB_TEMPLATE_RENDER',
  'SCOPE_OMT_SUBSCRIPTION_ADMIN_READ',
  'SCOPE_CONNECT_NON_SOCIAL_SHARED_READ',
  'SCOPE_CONNECT_READ',
  'SCOPE_DI_OAUTH_2_TOKEN_ADMIN',
  'ROLE_CONNECTUSER',
  'ROLE_FITNESS_USER',
  'ROLE_WELLNESS_USER'],
 'privacy': {'typeId': 2, 'typeKey': 'private'},
 'userPro': False,
 'hasVideo': False,
 'timeZoneId': 159,
 'beginTimestamp': 1736871165000,
 'sportTypeId': 2,
 'aerobicTrainingEffect': 3.0999999046325684,
 'anaerobicTrainingEffect': 0.800000011920929,
 'deviceId': 3441248959,
 'summarizedDiveInfo': {'summarizedDiveGases': []},
 'manufacturer': 'GARMIN',
 'lapCount': 1,
 'waterEstimated': 215.0,
 'minActivityLapDuration': 2154.448974609375,
 'aerobicTrainingEffectMessage': 'IMPROVING_AEROBIC_BASE_8',
 'anaerobicTrainingEffectMessage': 'NO_ANAEROBIC_BENEFIT_0',
 'splitSummaries': [],
 'hasSplits': False,
 'moderateIntensityMinutes': 6,
 'vigorousIntensityMinutes': 28,
 'hasHeatMap': False,
 'hrTimeInZone_0': 130.1,
 'hrTimeInZone_1': 138.0,
 'hrTimeInZone_2': 408.996,
 'hrTimeInZone_3': 1132.001,
 'hrTimeInZone_4': 345.352,
 'hrTimeInZone_5': 0.0,
 'purposeful': False,
 'manualActivity': False,
 'pr': False,
 'autoCalcCalories': False,
 'elevationCorrected': False,
 'atpActivity': False,
 'favorite': False,
 'decoDive': False,
 'parent': False}

In [17]:
activity_df = pd.DataFrame(garmin.get_activities_by_date(DATE_1, DATE_2))
activity_df.head(10)

,activityId,activityName,startTimeLocal,startTimeGMT,activityType,eventType,distance,duration,elapsedDuration,movingDuration,...,locationName,endLatitude,endLongitude,fastestSplit_1000,fastestSplit_1609,surfaceInterval,avgVerticalSpeed,floorsClimbed,floorsDescended,jumpCount
0,18007394591,Indoor Cycling,2025-01-14 16:12:45,2025-01-14 16:12:45,"{'typeId': 25, 'typeKey': 'indoor_cycling', 'p...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,2154.448975,2154.448975,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17993805679,Strength,2025-01-13 18:11:00,2025-01-13 18:11:00,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,2254.120117,2254.120117,2254.120117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17984702408,Strength,2025-01-12 15:53:41,2025-01-12 15:53:41,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,3246.406006,3246.406006,3244.812012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17975471544,Strength,2025-01-11 15:50:16,2025-01-11 15:50:16,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,4072.937988,4072.937988,4072.937988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17946851848,Strength,2025-01-08 11:04:55,2025-01-08 11:04:55,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,2659.792969,2659.792969,2657.576904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,17931673682,Strength,2025-01-06 15:48:10,2025-01-06 15:48:10,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,2201.655029,2201.655029,2201.655029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,17922348440,Strength,2025-01-05 12:53:49,2025-01-05 12:53:49,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,2359.886963,2359.886963,2359.886963,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,17896208759,Strength,2025-01-02 12:38:47,2025-01-02 12:38:47,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,2422.905029,2422.905029,2422.905029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,17880488360,Strength,2024-12-31 11:26:50,2024-12-31 11:26:50,"{'typeId': 13, 'typeKey': 'strength_training',...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",0.000000,3435.270996,3435.270996,3435.270996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,17874143662,Wealden Running,2024-12-30 15:59:36,2024-12-30 15:59:36,"{'typeId': 1, 'typeKey': 'running', 'parentTyp...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",3466.620117,1353.964966,1353.964966,1340.000000,...,Wealden,51.064376,0.167752,371.688995,616.401001,NaN,NaN,NaN,NaN,NaN